### ISSUE TITLE
rename to "cfep" from "conda-forge-enhancement-proposals"

### ISSUE THREAD

**Issue by ericdill** [conda-forge/cfep#14]
it is a pain to type in this url: github.com/conda-forge/conda-forge/conda-forge-enhancement-proposals

Other options that are simpler:

1.  github.com/conda-forge/cfep
2.  github.com/conda-forge/enhancement-proposals

Thoughts @conda-forge/core

**Comment by ocefpaf** [comment]
If we are going to make this easier to type let's go for `1`!

**Comment by scopatz** [comment]
Yeah, 1 works for me!

**Comment by mwcraig** [comment]
👍 for 1

**Comment by jakirkham** [comment]
1 👍

**Comment by sodre** [comment]
1 👍
