### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cfep#2]
I put this under BSD 3-Clause as we needed something and we use that license everywhere. Not sure if we want to keep that or not. Thoughts feedback?

cc @conda-forge/core

**Comment by scopatz** [comment]
I am pro BSD 3-Clause :)

**Comment by mwcraig** [comment]
Fine with me!

**Comment by patricksnape** [comment]
Good with me

**Comment by jjhelmus** [comment]
BSD is an odd license for documentation which is what this repository will mostly be.  Would an [open publication license](http://opencontent.org/openpub/) make more sense or public domain (or a more codified version like CC-0) as that is what is suggested for the CFEPs themselve

**Comment by ocefpaf** [comment]
I agree with @jjhelmus here. BSD is perfect for code but weird to interpret when it is used for docs. I am fine with public domain BTW.

**Comment by scopatz** [comment]
CC0 is far preferable to the public domain since not all jurisprudences have a notion of a public domain, and the fallback is the retention of personal ownership.  CC0 is a hardened version of public domain that applies everywhere.

**Comment by patricksnape** [comment]
Fair enough, I can see that. I am aware that many text sources often use [CC0](https://creativecommons.org/choose/zero/) as @scopatz mentioned, so I would also be happy with that.

**Comment by pelson** [comment]
CC 4.0 has been the license that conda-forge.github.io has taken (https://github.com/conda-forge/conda-forge.github.io/blob/master/index.html#L213). Happy to change that, but definitely advocate consistency. :+1: on a CC license - happy either way on the version.

**Comment by mwcraig** [comment]
I'd lean CC0 (Python PEPs are public domain).

Edit: CC0 for CFEPs, CC4 is completely appropriate for the website).

**Comment by jakirkham** [comment]
> CC0 for CFEPs, CC4 is completely appropriate for the website

👍 Agreed. As it seems like we want this to now be CC0, would someone like to submit a PR to change the license?

**Comment by pelson** [comment]
Since every CFEP has its own license statement at the bottom, I'm not too fussed if we maintain the repo BSD-3 label. There isn't (and shouldn't be) an awful lot else in the repo, but I don't believe it is causing any harm where it is (other than potential confusion, until the CFEP is actually *read*.

In the interest of closing off some issues, I'm going to go ahead and close. If somebody feels sufficiently strongly to submit a PR, I wouldn't hold it back, but equally, it isn't mission critical either. 😉
