### ISSUE TITLE
arm packages?

### ISSUE THREAD

**Issue by maxnoe** [conda-forge/cfep#4]
Is there a possibility to build arm7 packages (e.g. for the raspberry pi 2)?

As continuums packages are rather old, this would be really good.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge.github.io #239](https://github.com/conda-forge/conda-forge.github.io/issues/239) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jakirkham** [comment]
So this repo is for setting standards (enhancement proposals) in conda-forge (think [PEP](https://www.python.org/dev/peps/)s for conda-forge). This issue would be more appropriate on the webpage repo. Therefore I have moved it over there. Please discuss further on that issue tracker.
